"""Migration 2025-01-20_02-17-19

Revision ID: 96d766597915
Revises: 4c7b7cdffbd0
Create Date: 2025-01-20 02:17:20.086812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d766597915'
down_revision: Union[str, None] = '4c7b7cdffbd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.Integer(), nullable=True, comment='Идентификатор телеграм чата данного пользователя'), schema='data')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               comment='Уникальный username для входа в систему',
               existing_comment='Уникальный login для входа в систему',
               existing_nullable=False,
               schema='data')
    op.create_unique_constraint(None, 'users', ['telegram_chat_id'], schema='data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='data', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               comment='Уникальный login для входа в систему',
               existing_comment='Уникальный username для входа в систему',
               existing_nullable=False,
               schema='data')
    op.drop_column('users', 'telegram_chat_id', schema='data')
    # ### end Alembic commands ###
