"""Migration 2025-01-21_23-41-29

Revision ID: 9ae9ad7c7f76
Revises: 96d766597915
Create Date: 2025-01-21 23:41:29.834662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ae9ad7c7f76'
down_revision: Union[str, None] = '96d766597915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Дата и время создания записи пользователя',
               existing_nullable=True,
               schema='data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Дата и время создания записи пользователя',
               existing_nullable=True,
               schema='data')
    # ### end Alembic commands ###
