"""Migration 2025-01-26_02-09-30

Revision ID: 8072e52ad3e0
Revises: 
Create Date: 2025-01-26 02:09:31.258727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8072e52ad3e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False, comment='id для каждой роли'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='Название роли (например, admin, member)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='data',
    comment='Таблица ролей пользователей'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='id для каждого пользователя'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Имя пользователя'),
    sa.Column('birthday', sa.Date(), nullable=True, comment='Дата рождения'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='Ссылка на роль пользователя'),
    sa.Column('username', sa.String(length=255), nullable=False, comment='Уникальный username для входа в систему'),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=True, comment='Идентификатор телеграм чата данного пользователя'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Хэш пароля для аутентификации'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='Дата и время создания записи пользователя'),
    sa.ForeignKeyConstraint(['role_id'], ['data.role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id'),
    sa.UniqueConstraint('username'),
    schema='data',
    comment='Таблица пользователей, содержит информацию о пользователях системы'
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('amount', sa.Double(), nullable=False, comment='Сумма транзакции'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание транзакции'),
    sa.Column('is_income', sa.Boolean(), nullable=False, comment='Флаг для типа транзакции: True - доход, False - расход'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Ссылка на пользователя, который сделал транзакцию'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='Дата и время создания записи транзакции'),
    sa.ForeignKeyConstraint(['user_id'], ['data.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='data',
    comment='Объединенная таблица доходов и расходов пользователей'
    )
    # ### end Alembic commands ###

    #Основные роли в данном проекте
    op.execute("""
    INSERT INTO data.role (name) VALUES
        ('admin'),
        ('user');
    """)

    #Тестовые юзеры
    op.execute("""
    INSERT INTO data.users (name, role_id, birthday, username, password_hash, created_at)
    VALUES
        ('Админ',
         (select id from data.role where name = 'admin'), 
         '2000-01-01', 'admin', '$2b$12$tjjbHT4OI43H.D0CK4kVPeWz1TcTSLp4OsuS6LzG9Lw.UupvmvJxu', NOW()),
        ('Пользователь',
         (select id from data.role where name = 'user'), 
          '2000-02-02', 'user', '$2b$12$Gi25mIMEe3IEG.89lEgDueGEapib6VSGx1knmSpUKo1s64/.qMPTO', NOW());
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions', schema='data')
    op.drop_table('users', schema='data')
    op.drop_table('role', schema='data')
    # ### end Alembic commands ###
